# Generated by Django 5.0.7 on 2024-09-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_order_product_orderproduct_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
