# Generated by Django 5.0.7 on 2024-09-08 10:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_products_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
